services:
    db:
        image: mongo:5
        restart: "no"
        ports:
            - 27017:27017
        environment:
            MONGODB_DATABASE: biblioteca
        volumes:
            - ./mongo:/data/db